defaults:
  - override hydra/launcher: submitit_slurm

user: ${oc.env:USER}
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/seed${seed}/${obj}_steps${num_iterations}
    # dir: outputs/${now:%Y-%m-%d}/seed${seed}/${method}_R0${R0}_dim${ndim}_H${horizon}_prb${prb}_mutation_${mutation}replay_size${replay_sample_size}buffer_size${replay_buf_size}num_pop${population_size}elite${num_elites}


wandb: false
debug: false
seed: 0
array: ""
print_array_length: false
run: 0
save_path: results/

# MDP
min_blocks: 2
max_blocks: 8
sample_prob: 1
replay_mode: online
random_action_prob: 0.05
reward_exp: 10
reward_norm: 8
R_min: 0.1
early_stop_reg: 0.1
include_nblocks: false
ignore_parents: false

# Architecture
nemb: 256
num_conv_steps: 10
repr_type: block_graph
model_version: v4

# GFlowNet
floatX: float64
mbsize: 4
num_iterations: 6000
obj: fm
lr: 5e-4
opt_beta: 0.9
opt_beta2: 0.999
opt_epsilon: 1e-8
clip_grad: 0.
clip_loss: 0.
bootstrap_tau: 0
weight_decay: 0
leaf_coef: 10.
log_reg_c: 2.5e-5
balanced_loss: true
initial_log_Z: 30
subtb_lambda: 0.99
# Distributional GFlowNet
N: 16
quantile_dim: 256
nvec: 256
ts: false

# Evolution Guided GFlowNet
population_size: 10 # 25 might be good
num_eval_episodes: 4 # 1 seems just fine
num_elites: 2
tournament_size: 4
mutation: true
crossover_prob: 0.1
mutation_prob: 0.9
mutation_frac: 0.1
mutation_strength: 0.1
super_mutation_strength: 10
super_mutation_prob: 0.25 #0.25 is good
reset_prob: 0.1
weight_limit: 100000